services:
- type: web
  name: wizgrade
  env: docker
  dockerfilePath: ./Dockerfile
  healthCheckPath: /
  envVars:
  - key: DB_HOST
    fromService:
      type: pserv
      name: wizgrade-db
      property: host
  - key: DB_NAME
    fromService:
      type: pserv
      name: wizgrade-db
      property: database
  - key: DB_USER
    fromService:
      type: pserv
      name: wizgrade-db
      property: user
  - key: DB_PASSWORD
    fromService:
      type: pserv
      name: wizgrade-db
      property: password
  disks:
  - name: wizgrade-uploads
    mountPath: /var/www/html/wizGradePic
    sizeGB: 10

- type: pserv
  name: wizgrade-db
  env: mysql
  plan: free
  databaseName: wizgrade_db
  databaseUser: wizgrade_user
  envVars:
  - key: MYSQL_ROOT_PASSWORD
    generateValue: true
  - key: MYSQL_DATABASE
    value: wizgrade_db
  - key: MYSQL_USER
    value: wizgrade_user
  - key: MYSQL_PASSWORD
    generateValue: true
